'use strict';
const $=id=>document.getElementById(id);let model=PaperWeave.preset(),history=[],revision=0,loadSequence=0,previewURL=null,dirty=false;
function message(s){$('status').textContent=s;}
function render(focus=-1){$('size').value=model.size;$('palette').value=model.palette;const grid=$('grid');grid.style.gridTemplateColumns=`repeat(${model.size},1fr)`;grid.replaceChildren();model.cells.forEach((row,r)=>row.forEach((value,c)=>{const b=document.createElement('button');b.className='cell';b.dataset.index=r*model.size+c;b.tabIndex=(focus<0?r===0&&c===0:r*model.size+c===focus)?0:-1;b.textContent=value?'●':'○';b.setAttribute('aria-pressed',String(value));b.setAttribute('aria-label',`第${r+1}行 第${c+1}列 ${value?'竖条':'横条'}在上`);b.onclick=()=>change(PaperWeave.toggle(model,r,c),r*model.size+c);grid.append(b);}));if(focus>=0)grid.children[focus].focus();$('undo').disabled=!history.length;const data=PaperWeave.inspect(model);$('summary').textContent=`单元内最长 ${data.finiteMax} 格；跨接缝${data.cyclicMax===null?'存在无限延伸的线（'+data.unbounded.length+' 条）':'最长 '+data.cyclicMax+' 格'}。`;$('rows').replaceChildren();for(const line of data.lines){const tr=document.createElement('tr');for(const v of [(line.axis==='row'?'行':'列')+' '+(line.index+1),line.finite,line.unbounded?'无限':line.cyclic]){const td=document.createElement('td');td.textContent=v;tr.append(td);}$('rows').append(tr);}if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(new Blob([PaperWeave.svg(model)],{type:'image/svg+xml'}));$('image').src=previewURL;}
function change(next,focus=-1){history.push(model);if(history.length>100)history.shift();model=next;revision++;dirty=true;render(focus);message('已更新。最多可撤销100步；请保存作品。');}
$('grid').addEventListener('focusin',e=>{if(!e.target.matches('.cell'))return;for(const b of $('grid').children)b.tabIndex=b===e.target?0:-1;});
$('grid').addEventListener('keydown',e=>{const moves={ArrowLeft:-1,ArrowRight:1,ArrowUp:-model.size,ArrowDown:model.size};if(!e.target.matches('.cell')||!Object.hasOwn(moves,e.key))return;e.preventDefault();const i=Number(e.target.dataset.index),r=Math.floor(i/model.size),c=i%model.size;let j=i;if(e.key==='ArrowLeft'&&c>0||e.key==='ArrowRight'&&c<model.size-1||e.key==='ArrowUp'&&r>0||e.key==='ArrowDown'&&r<model.size-1)j+=moves[e.key];$('grid').children[j].focus();});
$('apply').onclick=()=>{if(dirty&&!confirm('应用起始图案会替换当前图案，可撤销。继续？'))return;change(PaperWeave.preset(Number($('size').value),$('preset').value,$('palette').value));};
$('palette').onchange=()=>change(PaperWeave.validate({...model,palette:$('palette').value}));$('invert').onclick=()=>change(PaperWeave.invert(model));$('undo').onclick=()=>{if(!history.length)return;model=history.pop();revision++;dirty=true;render();message('已撤销。');};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('save').onclick=()=>{download(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),'paper-weave-project.json');dirty=false;message('已请求保存；请确认文件已下载。');};$('svg').onclick=()=>download(new Blob([PaperWeave.svg(model)],{type:'image/svg+xml'}),'paper-weave.svg');
$('png').onclick=async()=>{const token=revision,svg=PaperWeave.svg(model),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));$('png').disabled=true;try{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=c.height=1200;c.getContext('2d').drawImage(img,0,0);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(token===revision&&blob)download(blob,'paper-weave.png');else message('图案已改变或导出失败，请重新导出。');}catch{message('无法生成PNG，请重试。');}finally{URL.revokeObjectURL(url);$('png').disabled=false;}};
$('load').onchange=async()=>{const file=$('load').files[0];$('load').value='';if(!file)return;const seq=++loadSequence,token=revision;$('load').disabled=true;try{if(file.size>32768||!file.name.toLowerCase().endsWith('.json'))throw Error('仅接受32 KiB以内的JSON作品。');const next=PaperWeave.validate(JSON.parse(await file.text()));if(seq!==loadSequence)return;if(token!==revision)throw Error('读取时图案已改变，未覆盖当前作品。');if(dirty&&!confirm('载入作品会替换当前图案，可撤销。继续？'))return;change(next);message('作品已载入，可撤销返回。');}catch(e){if(seq===loadSequence)message('未载入：'+e.message);}finally{if(seq===loadSequence)$('load').disabled=false;}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});render();
