'use strict';
(function(root){
 const sizes=[4,6,8,12],palettes={ink:['#28473e','#d6bd87'],clay:['#a44c38','#edcea1'],sea:['#236879','#bed6cf']};
 function validate(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.version!==1||!sizes.includes(value.size)||!Object.hasOwn(palettes,value.palette))throw Error('Invalid project header');const n=value.size;if(!Array.isArray(value.cells)||value.cells.length!==n||value.cells.some(r=>!Array.isArray(r)||r.length!==n||r.some(x=>typeof x!=='boolean')))throw Error('Invalid boolean tile');return {version:1,size:n,palette:value.palette,cells:value.cells.map(r=>r.slice())};}
 function preset(size=8,kind='plain',palette='ink'){if(!sizes.includes(size)||!['plain','diagonal','basket'].includes(kind)||!Object.hasOwn(palettes,palette))throw Error('Invalid preset');return validate({version:1,size,palette,cells:Array.from({length:size},(_,r)=>Array.from({length:size},(_,c)=>kind==='plain'?(r+c)%2===0:kind==='diagonal'?(r-c+size)%4<2:(Math.floor(r/2)+Math.floor(c/2))%2===0))});}
 function lineRuns(line){let max=1,run=1;for(let i=1;i<line.length;i++){run=line[i]===line[i-1]?run+1:1;max=Math.max(max,run);}if(line.every(x=>x===line[0]))return {finite:max,cyclic:null,unbounded:true};let prefix=1,suffix=1;while(prefix<line.length&&line[prefix]===line[0])prefix++;while(suffix<line.length&&line[line.length-1-suffix]===line.at(-1))suffix++;return {finite:max,cyclic:Math.max(max,line[0]===line.at(-1)?prefix+suffix:0),unbounded:false};}
 function inspect(value){const p=validate(value),lines=[];for(let i=0;i<p.size;i++){lines.push({axis:'row',index:i,...lineRuns(p.cells[i])});lines.push({axis:'column',index:i,...lineRuns(p.cells.map(r=>r[i]))});}return {finiteMax:Math.max(...lines.map(l=>l.finite)),cyclicMax:lines.some(l=>l.unbounded)?null:Math.max(...lines.map(l=>l.cyclic)),unbounded:lines.filter(l=>l.unbounded).map(l=>({axis:l.axis,index:l.index})),lines};}
 function toggle(value,row,col){const p=validate(value);if(!Number.isInteger(row)||!Number.isInteger(col)||row<0||col<0||row>=p.size||col>=p.size)throw Error('Invalid crossing');p.cells[row][col]=!p.cells[row][col];return p;}
 function invert(value){const p=validate(value);p.cells=p.cells.map(r=>r.map(x=>!x));return p;}
 function svg(value,repeats=3){const p=validate(value);if(!Number.isInteger(repeats)||repeats<1||repeats>3)throw Error('Invalid repeats');const n=p.size*repeats,step=960/n,[warp,weft]=palettes[p.palette];let s='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200" viewBox="0 0 1200 1200"><rect width="1200" height="1200" fill="#f5f0e4"/><g transform="translate(120 120)">';for(let r=0;r<n;r++)for(let c=0;c<n;c++){const x=c*step,y=r*step;s+=`<rect x="${x+step*.18}" y="${y}" width="${step*.64}" height="${step}" fill="${warp}"/><rect x="${x}" y="${y+step*.18}" width="${step}" height="${step*.64}" fill="${weft}"/>`;if(p.cells[r%p.size][c%p.size])s+=`<rect x="${x+step*.18}" y="${y}" width="${step*.64}" height="${step}" fill="${warp}"/>`;}return s+'</g></svg>';}
 const api={validate,preset,inspect,toggle,invert,svg};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.PaperWeave=Object.freeze(api);
})(globalThis);
